// Generated by .scripts/render-dashboard.mjs — do not edit by hand.
window.__CI_DATA__ = {
  "generatedAt": "2026-09-16T10:57:29.198Z",
  "trackedCount": 0,
  "competitors": [],
  "feed": [],
  "briefings": []
};
